apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: path-based-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: village-service
            port:
              number: 80

      - path: /village(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: village-service
            port:
              number: 80

      - path: /railway(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: railway-service
            port:
              number: 80

      - path: /factory(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: factory-service
            port:
              number: 80
